# Generated by Django 5.1.5 on 2026-09-11 10:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        ('member', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=30, unique=True, verbose_name='销售单号')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='应收金额')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='优惠金额')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='实收金额')),
                ('cost_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='成本金额')),
                ('pay_method', models.CharField(choices=[('cash', '现金'), ('wechat', '微信'), ('alipay', '支付宝'), ('card', '银行卡'), ('balance', '会员余额')], default='cash', max_length=20, verbose_name='支付方式')),
                ('points_earned', models.IntegerField(default=0, verbose_name='本次积分')),
                ('status', models.CharField(choices=[('done', '已完成'), ('returned', '已退货'), ('void', '已作废')], default='done', max_length=20, verbose_name='状态')),
                ('remark', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='销售时间')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='收银员')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='member.member', verbose_name='会员')),
            ],
            options={
                'verbose_name': '销售单',
                'verbose_name_plural': '销售单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, default='', max_length=100, verbose_name='商品名称')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='销售单价')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='成本单价')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='小计')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='goods.product', verbose_name='商品')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='销售单')),
            ],
            options={
                'verbose_name': '销售明细',
                'verbose_name_plural': '销售明细',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_no', models.CharField(max_length=30, unique=True, verbose_name='退货单号')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='退款金额')),
                ('reason', models.CharField(blank=True, default='', max_length=200, verbose_name='退货原因')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='退货时间')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_returns', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.sale', verbose_name='原销售单')),
            ],
            options={
                'verbose_name': '销售退货单',
                'verbose_name_plural': '销售退货单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='退货数量')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='退款单价')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='小计')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='goods.product', verbose_name='商品')),
                ('sale_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salereturn', verbose_name='退货单')),
            ],
            options={
                'verbose_name': '退货明细',
                'verbose_name_plural': '退货明细',
                'ordering': ['id'],
            },
        ),
    ]
