# Generated by Django 5.1.5 on 2026-09-11 10:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='等级名称')),
                ('discount', models.DecimalField(decimal_places=2, default=1.0, help_text='0.95 表示 95 折，1.00 表示无折扣', max_digits=4, verbose_name='折扣率')),
                ('point_rate', models.DecimalField(decimal_places=2, default=1.0, help_text='每消费 1 元获得 1 积分，倍率为 2 则获得 2 积分', max_digits=4, verbose_name='积分倍率')),
                ('min_points', models.IntegerField(default=0, verbose_name='升级所需积分')),
                ('remark', models.CharField(blank=True, default='', max_length=100, verbose_name='备注')),
            ],
            options={
                'verbose_name': '会员等级',
                'verbose_name_plural': '会员等级',
                'ordering': ['min_points'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(max_length=30, unique=True, verbose_name='会员卡号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='手机号')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女'), ('N', '未知')], default='N', max_length=2, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('points', models.IntegerField(default=0, verbose_name='积分余额')),
                ('total_points', models.IntegerField(default=0, verbose_name='累计积分')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='储值余额(元)')),
                ('total_spend', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='累计消费(元)')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='住址')),
                ('is_active', models.BooleanField(default=True, verbose_name='状态')),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='入会时间')),
                ('remark', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='member.memberlevel', verbose_name='会员等级')),
            ],
            options={
                'verbose_name': '会员',
                'verbose_name_plural': '会员',
                'ordering': ['-join_date'],
            },
        ),
    ]
