# Generated by Django 5.1.5 on 2026-09-11 10:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='分类编码')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='描述')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='供应商名称')),
                ('contact', models.CharField(blank=True, default='', max_length=50, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='地址')),
                ('bank_account', models.CharField(blank=True, default='', max_length=60, verbose_name='收款账号')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='合作中')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('barcode', models.CharField(max_length=50, unique=True, verbose_name='条形码')),
                ('spec', models.CharField(blank=True, default='', max_length=50, verbose_name='规格')),
                ('unit', models.CharField(default='件', max_length=10, verbose_name='单位')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='进价(元)')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='售价(元)')),
                ('stock', models.IntegerField(default=0, verbose_name='当前库存')),
                ('safety_stock', models.IntegerField(default=10, verbose_name='安全库存')),
                ('shelf_life_days', models.IntegerField(blank=True, null=True, verbose_name='保质期(天)')),
                ('status', models.CharField(choices=[('on', '在售'), ('off', '已下架')], default='on', max_length=10, verbose_name='状态')),
                ('remark', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='goods.category', verbose_name='所属分类')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='goods.supplier', verbose_name='默认供应商')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['-created_at'],
            },
        ),
    ]
