# Generated by Django 5.1.5 on 2026-09-11 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('account', '账号管理'), ('goods', '商品管理'), ('purchase', '采购管理'), ('sales', '销售管理'), ('member', '会员管理'), ('stock', '库存管理'), ('report', '统计报表'), ('system', '系统')], default='system', max_length=20, verbose_name='所属模块')),
                ('action', models.CharField(default='', max_length=50, verbose_name='操作类型')),
                ('detail', models.TextField(blank=True, default='', verbose_name='操作详情')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('purchase', '采购入库'), ('sale', '销售出库'), ('return', '退货入库'), ('check', '库存盘点'), ('loss', '报损'), ('manual', '手动调整')], default='manual', max_length=20, verbose_name='变动类型')),
                ('quantity', models.IntegerField(help_text='正数表示入库，负数表示出库', verbose_name='变动数量')),
                ('stock_before', models.IntegerField(default=0, verbose_name='变动前库存')),
                ('stock_after', models.IntegerField(default=0, verbose_name='变动后库存')),
                ('related_no', models.CharField(blank=True, default='', max_length=50, verbose_name='关联单号')),
                ('remark', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='变动时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_logs', to='goods.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '库存流水',
                'verbose_name_plural': '库存流水',
                'ordering': ['-created_at'],
            },
        ),
    ]
