# Generated by Django 5.1.5 on 2026-09-11 10:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=30, unique=True, verbose_name='采购单号')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='采购总额')),
                ('status', models.CharField(choices=[('draft', '待入库'), ('confirmed', '已入库'), ('canceled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('remark', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='入库时间')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='goods.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '采购单',
                'verbose_name_plural': '采购单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='采购数量')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='采购单价')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='小计')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='goods.product', verbose_name='商品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.purchaseorder', verbose_name='采购单')),
            ],
            options={
                'verbose_name': '采购明细',
                'verbose_name_plural': '采购明细',
                'ordering': ['id'],
            },
        ),
    ]
